<?php

use Illuminate\Database\Seeder;
use App\Municipality;

class municipalityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $municipio = [['fed_entity_id' => '1','key' => '1','name' => "Aguascalientes"],
            ['fed_entity_id' => '1','key' => '2','name' => "Asientos"],
            ['fed_entity_id' => '1','key' => '3','name' => "Calvillo"],
            ['fed_entity_id' => '1','key' => '4','name' => "Cosío"],
            ['fed_entity_id' => '1','key' => '5','name' => "Jesús María"],
            ['fed_entity_id' => '1','key' => '6','name' => "Pabellón de Arteaga"],
            ['fed_entity_id' => '1','key' => '7','name' => "Rincón de Romos"],
            ['fed_entity_id' => '1','key' => '8','name' => "San José de Gracia"],
            ['fed_entity_id' => '1','key' => '9','name' => "Tepezalá"],
            ['fed_entity_id' => '1','key' => '10','name' => "El Llano"],
            ['fed_entity_id' => '1','key' => '11','name' => "San Francisco de los Romo"],
            ['fed_entity_id' => '2','key' => '1','name' => "Ensenada"],
            ['fed_entity_id' => '2','key' => '2','name' => "Mexicali"],
            ['fed_entity_id' => '2','key' => '3','name' => "Tecate"],
            ['fed_entity_id' => '2','key' => '4','name' => "Tijuana"],
            ['fed_entity_id' => '2','key' => '5','name' => "Playas de Rosarito"],
            ['fed_entity_id' => '3','key' => '1','name' => "Comondú"],
            ['fed_entity_id' => '3','key' => '2','name' => "Mulegé"],
            ['fed_entity_id' => '3','key' => '3','name' => "La Paz"],
            ['fed_entity_id' => '3','key' => '8','name' => "Los Cabos"],
            ['fed_entity_id' => '3','key' => '9','name' => "Loreto"],
            ['fed_entity_id' => '4','key' => '1','name' => "Calkiní"],
            ['fed_entity_id' => '4','key' => '2','name' => "Campeche"],
            ['fed_entity_id' => '4','key' => '3','name' => "Carmen"],
            ['fed_entity_id' => '4','key' => '4','name' => "Champotón"],
            ['fed_entity_id' => '4','key' => '5','name' => "Hecelchakán"],
            ['fed_entity_id' => '4','key' => '6','name' => "Hopelchén"],
            ['fed_entity_id' => '4','key' => '7','name' => "Palizada"],
            ['fed_entity_id' => '4','key' => '8','name' => "Tenabo"],
            ['fed_entity_id' => '4','key' => '9','name' => "Escárcega"],
            ['fed_entity_id' => '4','key' => '10','name' => "Calakmul"],
            ['fed_entity_id' => '4','key' => '11','name' => "Candelaria"],
            ['fed_entity_id' => '5','key' => '1','name' => "Abasolo"],
            ['fed_entity_id' => '5','key' => '2','name' => "Acuña"],
            ['fed_entity_id' => '5','key' => '3','name' => "Allende"],
            ['fed_entity_id' => '5','key' => '4','name' => "Arteaga"],
            ['fed_entity_id' => '5','key' => '5','name' => "Candela"],
            ['fed_entity_id' => '5','key' => '6','name' => "Castaños"],
            ['fed_entity_id' => '5','key' => '7','name' => "Cuatro Ciénegas"],
            ['fed_entity_id' => '5','key' => '8','name' => "Escobedo"],
            ['fed_entity_id' => '5','key' => '9','name' => "Francisco I. Madero"],
            ['fed_entity_id' => '5','key' => '10','name' => "Frontera"],
            ['fed_entity_id' => '5','key' => '11','name' => "General Cepeda"],
            ['fed_entity_id' => '5','key' => '12','name' => "Guerrero"],
            ['fed_entity_id' => '5','key' => '13','name' => "Hidalgo"],
            ['fed_entity_id' => '5','key' => '14','name' => "Jiménez"],
            ['fed_entity_id' => '5','key' => '15','name' => "Juárez"],
            ['fed_entity_id' => '5','key' => '16','name' => "Lamadrid"],
            ['fed_entity_id' => '5','key' => '17','name' => "Matamoros"],
            ['fed_entity_id' => '5','key' => '18','name' => "Monclova"],
            ['fed_entity_id' => '5','key' => '19','name' => "Morelos"],
            ['fed_entity_id' => '5','key' => '20','name' => "Múzquiz"],
            ['fed_entity_id' => '5','key' => '21','name' => "Nadadores"],
            ['fed_entity_id' => '5','key' => '22','name' => "Nava"],
            ['fed_entity_id' => '5','key' => '23','name' => "Ocampo"],
            ['fed_entity_id' => '5','key' => '24','name' => "Parras"],
            ['fed_entity_id' => '5','key' => '25','name' => "Piedras Negras"],
            ['fed_entity_id' => '5','key' => '26','name' => "Progreso"],
            ['fed_entity_id' => '5','key' => '27','name' => "Ramos Arizpe"],
            ['fed_entity_id' => '5','key' => '28','name' => "Sabinas"],
            ['fed_entity_id' => '5','key' => '29','name' => "Sacramento"],
            ['fed_entity_id' => '5','key' => '30','name' => "Saltillo"],
            ['fed_entity_id' => '5','key' => '31','name' => "San Buenaventura"],
            ['fed_entity_id' => '5','key' => '32','name' => "San Juan de Sabinas"],
            ['fed_entity_id' => '5','key' => '33','name' => "San Pedro"],
            ['fed_entity_id' => '5','key' => '34','name' => "Sierra Mojada"],
            ['fed_entity_id' => '5','key' => '35','name' => "Torreón"],
            ['fed_entity_id' => '5','key' => '36','name' => "Viesca"],
            ['fed_entity_id' => '5','key' => '37','name' => "Villa Unión"],
            ['fed_entity_id' => '5','key' => '38','name' => "Zaragoza"],
            ['fed_entity_id' => '6','key' => '1','name' => "Armería"],
            ['fed_entity_id' => '6','key' => '2','name' => "Colima"],
            ['fed_entity_id' => '6','key' => '3','name' => "Comala"],
            ['fed_entity_id' => '6','key' => '4','name' => "Coquimatlán"],
            ['fed_entity_id' => '6','key' => '5','name' => "Cuauhtémoc"],
            ['fed_entity_id' => '6','key' => '6','name' => "Ixtlahuacán"],
            ['fed_entity_id' => '6','key' => '7','name' => "Manzanillo"],
            ['fed_entity_id' => '6','key' => '8','name' => "Minatitlán"],
            ['fed_entity_id' => '6','key' => '9','name' => "Tecomán"],
            ['fed_entity_id' => '6','key' => '10','name' => "Villa de Álvarez"],
            ['fed_entity_id' => '7','key' => '1','name' => "Acacoyagua"],
            ['fed_entity_id' => '7','key' => '2','name' => "Acala"],
            ['fed_entity_id' => '7','key' => '3','name' => "Acapetahua"],
            ['fed_entity_id' => '7','key' => '4','name' => "Altamirano"],
            ['fed_entity_id' => '7','key' => '5','name' => "Amatán"],
            ['fed_entity_id' => '7','key' => '6','name' => "Amatenango de la Frontera"],
            ['fed_entity_id' => '7','key' => '7','name' => "Amatenango del Valle"],
            ['fed_entity_id' => '7','key' => '8','name' => "Angel Albino Corzo"],
            ['fed_entity_id' => '7','key' => '9','name' => "Arriaga"],
            ['fed_entity_id' => '7','key' => '10','name' => "Bejucal de Ocampo"],
            ['fed_entity_id' => '7','key' => '11','name' => "Bella Vista"],
            ['fed_entity_id' => '7','key' => '12','name' => "Berriozábal"],
            ['fed_entity_id' => '7','key' => '13','name' => "Bochil"],
            ['fed_entity_id' => '7','key' => '14','name' => "El Bosque"],
            ['fed_entity_id' => '7','key' => '15','name' => "Cacahoatán"],
            ['fed_entity_id' => '7','key' => '16','name' => "Catazajá"],
            ['fed_entity_id' => '7','key' => '17','name' => "Cintalapa"],
            ['fed_entity_id' => '7','key' => '18','name' => "Coapilla"],
            ['fed_entity_id' => '7','key' => '19','name' => "Comitán de Domínguez"],
            ['fed_entity_id' => '7','key' => '20','name' => "La Concordia"],
            ['fed_entity_id' => '7','key' => '21','name' => "Copainalá"],
            ['fed_entity_id' => '7','key' => '22','name' => "Chalchihuitán"],
            ['fed_entity_id' => '7','key' => '23','name' => "Chamula"],
            ['fed_entity_id' => '7','key' => '24','name' => "Chanal"],
            ['fed_entity_id' => '7','key' => '25','name' => "Chapultenango"],
            ['fed_entity_id' => '7','key' => '26','name' => "Chenalhó"],
            ['fed_entity_id' => '7','key' => '27','name' => "Chiapa de Corzo"],
            ['fed_entity_id' => '7','key' => '28','name' => "Chiapilla"],
            ['fed_entity_id' => '7','key' => '29','name' => "Chicoasén"],
            ['fed_entity_id' => '7','key' => '30','name' => "Chicomuselo"],
            ['fed_entity_id' => '7','key' => '31','name' => "Chilón"],
            ['fed_entity_id' => '7','key' => '32','name' => "Escuintla"],
            ['fed_entity_id' => '7','key' => '33','name' => "Francisco León"],
            ['fed_entity_id' => '7','key' => '34','name' => "Frontera Comalapa"],
            ['fed_entity_id' => '7','key' => '35','name' => "Frontera Hidalgo"],
            ['fed_entity_id' => '7','key' => '36','name' => "La Grandeza"],
            ['fed_entity_id' => '7','key' => '37','name' => "Huehuetán"],
            ['fed_entity_id' => '7','key' => '38','name' => "Huixtán"],
            ['fed_entity_id' => '7','key' => '39','name' => "Huitiupán"],
            ['fed_entity_id' => '7','key' => '40','name' => "Huixtla"],
            ['fed_entity_id' => '7','key' => '12','name' => "La Independencia"],
            ['fed_entity_id' => '7','key' => '13','name' => "Ixhuatán"],
            ['fed_entity_id' => '7','key' => '14','name' => "Ixtacomitán"],
            ['fed_entity_id' => '7','key' => '15','name' => "Ixtapa"],
            ['fed_entity_id' => '7','key' => '45','name' => "Ixtapangajoya"],
            ['fed_entity_id' => '7','key' => '46','name' => "Jiquipilas"],
            ['fed_entity_id' => '7','key' => '47','name' => "Jitotol"],
            ['fed_entity_id' => '7','key' => '48','name' => "Juárez"],
            ['fed_entity_id' => '7','key' => '49','name' => "Larráinzar"],
            ['fed_entity_id' => '7','key' => '50','name' => "La Libertad"],
            ['fed_entity_id' => '7','key' => '51','name' => "Mapastepec"],
            ['fed_entity_id' => '7','key' => '52','name' => "Las Margaritas"],
            ['fed_entity_id' => '7','key' => '53','name' => "Mazapa de Madero"],
            ['fed_entity_id' => '7','key' => '54','name' => "Mazatán"],
            ['fed_entity_id' => '7','key' => '55','name' => "Metapa"],
            ['fed_entity_id' => '7','key' => '56','name' => "Mitontic"],
            ['fed_entity_id' => '7','key' => '57','name' => "Motozintla"],
            ['fed_entity_id' => '7','key' => '58','name' => "Nicolás Ruíz"],
            ['fed_entity_id' => '7','key' => '59','name' => "Ocosingo"],
            ['fed_entity_id' => '7','key' => '60','name' => "Ocotepec"],
            ['fed_entity_id' => '7','key' => '61','name' => "Ocozocoautla de Espinosa"],
            ['fed_entity_id' => '7','key' => '62','name' => "Ostuacán"],
            ['fed_entity_id' => '7','key' => '63','name' => "Osumacinta"],
            ['fed_entity_id' => '7','key' => '64','name' => "Oxchuc"],
            ['fed_entity_id' => '7','key' => '65','name' => "Palenque"],
            ['fed_entity_id' => '7','key' => '66','name' => "Pantelhó"],
            ['fed_entity_id' => '7','key' => '67','name' => "Pantepec"],
            ['fed_entity_id' => '7','key' => '68','name' => "Pichucalco"],
            ['fed_entity_id' => '7','key' => '69','name' => "Pijijiapan"],
            ['fed_entity_id' => '7','key' => '70','name' => "El Porvenir"],
            ['fed_entity_id' => '7','key' => '71','name' => "Villa Comaltitlán"],
            ['fed_entity_id' => '7','key' => '72','name' => "Pueblo Nuevo Solistahuacán"],
            ['fed_entity_id' => '7','key' => '73','name' => "Rayón"],
            ['fed_entity_id' => '7','key' => '74','name' => "Reforma"],
            ['fed_entity_id' => '7','key' => '75','name' => "Las Rosas"],
            ['fed_entity_id' => '7','key' => '76','name' => "Sabanilla"],
            ['fed_entity_id' => '7','key' => '77','name' => "Salto de Agua"],
            ['fed_entity_id' => '7','key' => '78','name' => "San Cristóbal de las Casas"],
            ['fed_entity_id' => '7','key' => '79','name' => "San Fernando"],
            ['fed_entity_id' => '7','key' => '80','name' => "Siltepec"],
            ['fed_entity_id' => '7','key' => '81','name' => "Simojovel"],
            ['fed_entity_id' => '7','key' => '82','name' => "Sitalá"],
            ['fed_entity_id' => '7','key' => '83','name' => "Socoltenango"],
            ['fed_entity_id' => '7','key' => '84','name' => "Solosuchiapa"],
            ['fed_entity_id' => '7','key' => '85','name' => "Soyaló"],
            ['fed_entity_id' => '7','key' => '86','name' => "Suchiapa"],
            ['fed_entity_id' => '7','key' => '87','name' => "Suchiate"],
            ['fed_entity_id' => '7','key' => '88','name' => "Sunuapa"],
            ['fed_entity_id' => '7','key' => '89','name' => "Tapachula"],
            ['fed_entity_id' => '7','key' => '90','name' => "Tapalapa"],
            ['fed_entity_id' => '7','key' => '91','name' => "Tapilula"],
            ['fed_entity_id' => '7','key' => '92','name' => "Tecpatán"],
            ['fed_entity_id' => '7','key' => '93','name' => "Tenejapa"],
            ['fed_entity_id' => '7','key' => '94','name' => "Teopisca"],
            ['fed_entity_id' => '7','key' => '96','name' => "Tila"],
            ['fed_entity_id' => '7','key' => '97','name' => "Tonalá"],
            ['fed_entity_id' => '7','key' => '98','name' => "Totolapa"],
            ['fed_entity_id' => '7','key' => '99','name' => "La Trinitaria"],
            ['fed_entity_id' => '7','key' => '100','name' => "Tumbalá"],
            ['fed_entity_id' => '7','key' => '101','name' => "Tuxtla Gutiérrez"],
            ['fed_entity_id' => '7','key' => '102','name' => "Tuxtla Chico"],
            ['fed_entity_id' => '7','key' => '103','name' => "Tuzantán"],
            ['fed_entity_id' => '7','key' => '104','name' => "Tzimol"],
            ['fed_entity_id' => '7','key' => '105','name' => "Unión Juárez"],
            ['fed_entity_id' => '7','key' => '106','name' => "Venustiano Carranza"],
            ['fed_entity_id' => '7','key' => '107','name' => "Villa Corzo"],
            ['fed_entity_id' => '7','key' => '108','name' => "Villaflores"],
            ['fed_entity_id' => '7','key' => '109','name' => "Yajalón"],
            ['fed_entity_id' => '7','key' => '110','name' => "San Lucas"],
            ['fed_entity_id' => '7','key' => '111','name' => "Zinacantán"],
            ['fed_entity_id' => '7','key' => '112','name' => "San Juan Cancuc"],
            ['fed_entity_id' => '7','key' => '113','name' => "Aldama"],
            ['fed_entity_id' => '7','key' => '114','name' => "Benemérito de las Américas"],
            ['fed_entity_id' => '7','key' => '115','name' => "Maravilla Tenejapa"],
            ['fed_entity_id' => '7','key' => '116','name' => "Marqués de Comillas"],
            ['fed_entity_id' => '7','key' => '117','name' => "Montecristo de Guerrero"],
            ['fed_entity_id' => '7','key' => '118','name' => "San Andrés Duraznal"],
            ['fed_entity_id' => '7','key' => '119','name' => "Santiago el Pinar"],
            ['fed_entity_id' => '8','key' => '1','name' => "Ahumada"],
            ['fed_entity_id' => '8','key' => '2','name' => "Aldama"],
            ['fed_entity_id' => '8','key' => '3','name' => "Allende"],
            ['fed_entity_id' => '8','key' => '4','name' => "Aquiles Serdán"],
            ['fed_entity_id' => '8','key' => '5','name' => "Ascensión"],
            ['fed_entity_id' => '8','key' => '6','name' => "Bachíniva"],
            ['fed_entity_id' => '8','key' => '7','name' => "Balleza"],
            ['fed_entity_id' => '8','key' => '8','name' => "Batopilas"],
            ['fed_entity_id' => '8','key' => '9','name' => "Bocoyna"],
            ['fed_entity_id' => '8','key' => '10','name' => "Buenaventura"],
            ['fed_entity_id' => '8','key' => '11','name' => "Camargo"],
            ['fed_entity_id' => '8','key' => '12','name' => "Carichí"],
            ['fed_entity_id' => '8','key' => '13','name' => "Casas Grandes"],
            ['fed_entity_id' => '8','key' => '14','name' => "Coronado"],
            ['fed_entity_id' => '8','key' => '15','name' => "Coyame del Sotol"],
            ['fed_entity_id' => '8','key' => '16','name' => "La Cruz"],
            ['fed_entity_id' => '8','key' => '17','name' => "Cuauhtémoc"],
            ['fed_entity_id' => '8','key' => '18','name' => "Cusihuiriachi"],
            ['fed_entity_id' => '8','key' => '19','name' => "Chihuahua"],
            ['fed_entity_id' => '8','key' => '20','name' => "Chínipas"],
            ['fed_entity_id' => '8','key' => '21','name' => "Delicias"],
            ['fed_entity_id' => '8','key' => '22','name' => "Dr. Belisario Domínguez"],
            ['fed_entity_id' => '8','key' => '23','name' => "Galeana"],
            ['fed_entity_id' => '8','key' => '24','name' => "Santa Isabel"],
            ['fed_entity_id' => '8','key' => '25','name' => "Gómez Farías"],
            ['fed_entity_id' => '8','key' => '26','name' => "Gran Morelos"],
            ['fed_entity_id' => '8','key' => '27','name' => "Guachochi"],
            ['fed_entity_id' => '8','key' => '28','name' => "Guadalupe"],
            ['fed_entity_id' => '8','key' => '29','name' => "Guadalupe y Calvo"],
            ['fed_entity_id' => '8','key' => '30','name' => "Guazapares"],
            ['fed_entity_id' => '8','key' => '31','name' => "Guerrero"],
            ['fed_entity_id' => '8','key' => '32','name' => "Hidalgo del Parral"],
            ['fed_entity_id' => '8','key' => '33','name' => "Huejotitán"],
            ['fed_entity_id' => '8','key' => '34','name' => "Ignacio Zaragoza"],
            ['fed_entity_id' => '8','key' => '35','name' => "Janos"],
            ['fed_entity_id' => '8','key' => '36','name' => "Jiménez"],
            ['fed_entity_id' => '8','key' => '37','name' => "Juárez"],
            ['fed_entity_id' => '8','key' => '38','name' => "Julimes"],
            ['fed_entity_id' => '8','key' => '39','name' => "López"],
            ['fed_entity_id' => '8','key' => '40','name' => "Madera"],
            ['fed_entity_id' => '8','key' => '12','name' => "Maguarichi"],
            ['fed_entity_id' => '8','key' => '13','name' => "Manuel Benavides"],
            ['fed_entity_id' => '8','key' => '14','name' => "Matachí"],
            ['fed_entity_id' => '8','key' => '15','name' => "Matamoros"],
            ['fed_entity_id' => '8','key' => '45','name' => "Meoqui"],
            ['fed_entity_id' => '8','key' => '46','name' => "Morelos"],
            ['fed_entity_id' => '8','key' => '47','name' => "Moris"],
            ['fed_entity_id' => '8','key' => '48','name' => "Namiquipa"],
            ['fed_entity_id' => '8','key' => '49','name' => "Nonoava"],
            ['fed_entity_id' => '8','key' => '50','name' => "Nuevo Casas Grandes"],
            ['fed_entity_id' => '8','key' => '51','name' => "Ocampo"],
            ['fed_entity_id' => '8','key' => '52','name' => "Ojinaga"],
            ['fed_entity_id' => '8','key' => '53','name' => "Praxedis G. Guerrero"],
            ['fed_entity_id' => '8','key' => '54','name' => "Riva Palacio"],
            ['fed_entity_id' => '8','key' => '55','name' => "Rosales"],
            ['fed_entity_id' => '8','key' => '56','name' => "Rosario"],
            ['fed_entity_id' => '8','key' => '57','name' => "San Francisco de Borja"],
            ['fed_entity_id' => '8','key' => '58','name' => "San Francisco de Conchos"],
            ['fed_entity_id' => '8','key' => '59','name' => "San Francisco del Oro"],
            ['fed_entity_id' => '8','key' => '60','name' => "Santa Bárbara"],
            ['fed_entity_id' => '8','key' => '61','name' => "Satevó"],
            ['fed_entity_id' => '8','key' => '62','name' => "Saucillo"],
            ['fed_entity_id' => '8','key' => '63','name' => "Temósachic"],
            ['fed_entity_id' => '8','key' => '64','name' => "El Tule"],
            ['fed_entity_id' => '8','key' => '65','name' => "Urique"],
            ['fed_entity_id' => '8','key' => '66','name' => "Uruachi"],
            ['fed_entity_id' => '8','key' => '67','name' => "Valle de Zaragoza"],
            ['fed_entity_id' => '9','key' => '2','name' => "Azcapotzalco"],
            ['fed_entity_id' => '9','key' => '3','name' => "Coyoacán"],
            ['fed_entity_id' => '9','key' => '4','name' => "Cuajimalpa de Morelos"],
            ['fed_entity_id' => '9','key' => '5','name' => "Gustavo A. Madero"],
            ['fed_entity_id' => '9','key' => '6','name' => "Iztacalco"],
            ['fed_entity_id' => '9','key' => '7','name' => "Iztapalapa"],
            ['fed_entity_id' => '9','key' => '8','name' => "La Magdalena Contreras"],
            ['fed_entity_id' => '9','key' => '9','name' => "Milpa Alta"],
            ['fed_entity_id' => '9','key' => '10','name' => "Álvaro Obregón"],
            ['fed_entity_id' => '9','key' => '11','name' => "Tláhuac"],
            ['fed_entity_id' => '9','key' => '12','name' => "Tlalpan"],
            ['fed_entity_id' => '9','key' => '13','name' => "Xochimilco"],
            ['fed_entity_id' => '9','key' => '14','name' => "Benito Juárez"],
            ['fed_entity_id' => '9','key' => '15','name' => "Cuauhtémoc"],
            ['fed_entity_id' => '9','key' => '16','name' => "Miguel Hidalgo"],
            ['fed_entity_id' => '9','key' => '17','name' => "Venustiano Carranza"],
            ['fed_entity_id' => '10','key' => '1','name' => "Canatlán"],
            ['fed_entity_id' => '10','key' => '2','name' => "Canelas"],
            ['fed_entity_id' => '10','key' => '3','name' => "Coneto de Comonfort"],
            ['fed_entity_id' => '10','key' => '4','name' => "Cuencamé"],
            ['fed_entity_id' => '10','key' => '5','name' => "Durango"],
            ['fed_entity_id' => '10','key' => '6','name' => "General Simón Bolívar"],
            ['fed_entity_id' => '10','key' => '7','name' => "Gómez Palacio"],
            ['fed_entity_id' => '10','key' => '8','name' => "Guadalupe Victoria"],
            ['fed_entity_id' => '10','key' => '9','name' => "Guanaceví"],
            ['fed_entity_id' => '10','key' => '10','name' => "Hidalgo"],
            ['fed_entity_id' => '10','key' => '11','name' => "Indé"],
            ['fed_entity_id' => '10','key' => '12','name' => "Lerdo"],
            ['fed_entity_id' => '10','key' => '13','name' => "Mapimí"],
            ['fed_entity_id' => '10','key' => '14','name' => "Mezquital"],
            ['fed_entity_id' => '10','key' => '15','name' => "Nazas"],
            ['fed_entity_id' => '10','key' => '16','name' => "Nombre de Dios"],
            ['fed_entity_id' => '10','key' => '17','name' => "Ocampo"],
            ['fed_entity_id' => '10','key' => '18','name' => "El Oro"],
            ['fed_entity_id' => '10','key' => '19','name' => "Otáez"],
            ['fed_entity_id' => '10','key' => '20','name' => "Pánuco de Coronado"],
            ['fed_entity_id' => '10','key' => '21','name' => "Peñón Blanco"],
            ['fed_entity_id' => '10','key' => '22','name' => "Poanas"],
            ['fed_entity_id' => '10','key' => '23','name' => "Pueblo Nuevo"],
            ['fed_entity_id' => '10','key' => '24','name' => "Rodeo"],
            ['fed_entity_id' => '10','key' => '25','name' => "San Bernardo"],
            ['fed_entity_id' => '10','key' => '26','name' => "San Dimas"],
            ['fed_entity_id' => '10','key' => '27','name' => "San Juan de Guadalupe"],
            ['fed_entity_id' => '10','key' => '28','name' => "San Juan del Río"],
            ['fed_entity_id' => '10','key' => '29','name' => "San Luis del Cordero"],
            ['fed_entity_id' => '10','key' => '30','name' => "San Pedro del Gallo"],
            ['fed_entity_id' => '10','key' => '31','name' => "Santa Clara"],
            ['fed_entity_id' => '10','key' => '32','name' => "Santiago Papasquiaro"],
            ['fed_entity_id' => '10','key' => '33','name' => "Súchil"],
            ['fed_entity_id' => '10','key' => '34','name' => "Tamazula"],
            ['fed_entity_id' => '10','key' => '35','name' => "Tepehuanes"],
            ['fed_entity_id' => '10','key' => '36','name' => "Tlahualilo"],
            ['fed_entity_id' => '10','key' => '37','name' => "Topia"],
            ['fed_entity_id' => '10','key' => '38','name' => "Vicente Guerrero"],
            ['fed_entity_id' => '10','key' => '39','name' => "Nuevo Ideal"],
            ['fed_entity_id' => '11','key' => '1','name' => "Abasolo"],
            ['fed_entity_id' => '11','key' => '2','name' => "Acámbaro"],
            ['fed_entity_id' => '11','key' => '3','name' => "San Miguel de Allende"],
            ['fed_entity_id' => '11','key' => '4','name' => "Apaseo el Alto"],
            ['fed_entity_id' => '11','key' => '5','name' => "Apaseo el Grande"],
            ['fed_entity_id' => '11','key' => '6','name' => "Atarjea"],
            ['fed_entity_id' => '11','key' => '7','name' => "Celaya"],
            ['fed_entity_id' => '11','key' => '8','name' => "Manuel Doblado"],
            ['fed_entity_id' => '11','key' => '9','name' => "Comonfort"],
            ['fed_entity_id' => '11','key' => '10','name' => "Coroneo"],
            ['fed_entity_id' => '11','key' => '11','name' => "Cortazar"],
            ['fed_entity_id' => '11','key' => '12','name' => "Cuerámaro"],
            ['fed_entity_id' => '11','key' => '13','name' => "Doctor Mora"],
            ['fed_entity_id' => '11','key' => '14','name' => "Dolores Hidalgo Cuna de la Independencia Nacional"],
            ['fed_entity_id' => '11','key' => '15','name' => "Guanajuato"],
            ['fed_entity_id' => '11','key' => '16','name' => "Huanímaro"],
            ['fed_entity_id' => '11','key' => '17','name' => "Irapuato"],
            ['fed_entity_id' => '11','key' => '18','name' => "Jaral del Progreso"],
            ['fed_entity_id' => '11','key' => '19','name' => "Jerécuaro"],
            ['fed_entity_id' => '11','key' => '20','name' => "León"],
            ['fed_entity_id' => '11','key' => '21','name' => "Moroleón"],
            ['fed_entity_id' => '11','key' => '22','name' => "Ocampo"],
            ['fed_entity_id' => '11','key' => '23','name' => "Pénjamo"],
            ['fed_entity_id' => '11','key' => '24','name' => "Pueblo Nuevo"],
            ['fed_entity_id' => '11','key' => '25','name' => "Purísima del Rincón"],
            ['fed_entity_id' => '11','key' => '26','name' => "Romita"],
            ['fed_entity_id' => '11','key' => '27','name' => "Salamanca"],
            ['fed_entity_id' => '11','key' => '28','name' => "Salvatierra"],
            ['fed_entity_id' => '11','key' => '29','name' => "San Diego de la Unión"],
            ['fed_entity_id' => '11','key' => '30','name' => "San Felipe"],
            ['fed_entity_id' => '11','key' => '31','name' => "San Francisco del Rincón"],
            ['fed_entity_id' => '11','key' => '32','name' => "San José Iturbide"],
            ['fed_entity_id' => '11','key' => '33','name' => "San Luis de la Paz"],
            ['fed_entity_id' => '11','key' => '34','name' => "Santa Catarina"],
            ['fed_entity_id' => '11','key' => '35','name' => "Santa Cruz de Juventino Rosas"],
            ['fed_entity_id' => '11','key' => '36','name' => "Santiago Maravatío"],
            ['fed_entity_id' => '11','key' => '37','name' => "Silao"],
            ['fed_entity_id' => '11','key' => '38','name' => "Tarandacuao"],
            ['fed_entity_id' => '11','key' => '39','name' => "Tarimoro"],
            ['fed_entity_id' => '11','key' => '40','name' => "Tierra Blanca"],
            ['fed_entity_id' => '11','key' => '12','name' => "Uriangato"],
            ['fed_entity_id' => '11','key' => '13','name' => "Valle de Santiago"],
            ['fed_entity_id' => '11','key' => '14','name' => "Victoria"],
            ['fed_entity_id' => '11','key' => '15','name' => "Villagrán"],
            ['fed_entity_id' => '11','key' => '45','name' => "Xichú"],
            ['fed_entity_id' => '11','key' => '46','name' => "Yuriria"],
            ['fed_entity_id' => '12','key' => '1','name' => "Acapulco de Juárez"],
            ['fed_entity_id' => '12','key' => '2','name' => "Ahuacuotzingo"],
            ['fed_entity_id' => '12','key' => '3','name' => "Ajuchitlán del Progreso"],
            ['fed_entity_id' => '12','key' => '4','name' => "Alcozauca de Guerrero"],
            ['fed_entity_id' => '12','key' => '5','name' => "Alpoyeca"],
            ['fed_entity_id' => '12','key' => '6','name' => "Apaxtla"],
            ['fed_entity_id' => '12','key' => '7','name' => "Arcelia"],
            ['fed_entity_id' => '12','key' => '8','name' => "Atenango del Río"],
            ['fed_entity_id' => '12','key' => '9','name' => "Atlamajalcingo del Monte"],
            ['fed_entity_id' => '12','key' => '10','name' => "Atlixtac"],
            ['fed_entity_id' => '12','key' => '11','name' => "Atoyac de Álvarez"],
            ['fed_entity_id' => '12','key' => '12','name' => "Ayutla de los Libres"],
            ['fed_entity_id' => '12','key' => '13','name' => "Azoyú"],
            ['fed_entity_id' => '12','key' => '14','name' => "Benito Juárez"],
            ['fed_entity_id' => '12','key' => '15','name' => "Buenavista de Cuéllar"],
            ['fed_entity_id' => '12','key' => '16','name' => "Coahuayutla de José María Izazaga"],
            ['fed_entity_id' => '12','key' => '17','name' => "Cocula"],
            ['fed_entity_id' => '12','key' => '18','name' => "Copala"],
            ['fed_entity_id' => '12','key' => '19','name' => "Copalillo"],
            ['fed_entity_id' => '12','key' => '20','name' => "Copanatoyac"],
            ['fed_entity_id' => '12','key' => '21','name' => "Coyuca de Benítez"],
            ['fed_entity_id' => '12','key' => '22','name' => "Coyuca de Catalán"],
            ['fed_entity_id' => '12','key' => '23','name' => "Cuajinicuilapa"],
            ['fed_entity_id' => '12','key' => '24','name' => "Cualác"],
            ['fed_entity_id' => '12','key' => '25','name' => "Cuautepec"],
            ['fed_entity_id' => '12','key' => '26','name' => "Cuetzala del Progreso"],
            ['fed_entity_id' => '12','key' => '27','name' => "Cutzamala de Pinzón"],
            ['fed_entity_id' => '12','key' => '28','name' => "Chilapa de Álvarez"],
            ['fed_entity_id' => '12','key' => '29','name' => "Chilpancingo de los Bravo"],
            ['fed_entity_id' => '12','key' => '30','name' => "Florencio Villarreal"],
            ['fed_entity_id' => '12','key' => '31','name' => "General Canuto A. Neri"],
            ['fed_entity_id' => '12','key' => '32','name' => "General Heliodoro Castillo"],
            ['fed_entity_id' => '12','key' => '33','name' => "Huamuxtitlán"],
            ['fed_entity_id' => '12','key' => '34','name' => "Huitzuco de los Figueroa"],
            ['fed_entity_id' => '12','key' => '35','name' => "Iguala de la Independencia"],
            ['fed_entity_id' => '12','key' => '36','name' => "Igualapa"],
            ['fed_entity_id' => '12','key' => '37','name' => "Ixcateopan de Cuauhtémoc"],
            ['fed_entity_id' => '12','key' => '38','name' => "Zihuatanejo de Azueta"],
            ['fed_entity_id' => '12','key' => '39','name' => "Juan R. Escudero"],
            ['fed_entity_id' => '12','key' => '40','name' => "Leonardo Bravo"],
            ['fed_entity_id' => '12','key' => '12','name' => "Malinaltepec"],
            ['fed_entity_id' => '12','key' => '13','name' => "Mártir de Cuilapan"],
            ['fed_entity_id' => '12','key' => '14','name' => "Metlatónoc"],
            ['fed_entity_id' => '12','key' => '15','name' => "Mochitlán"],
            ['fed_entity_id' => '12','key' => '45','name' => "Olinalá"],
            ['fed_entity_id' => '12','key' => '46','name' => "Ometepec"],
            ['fed_entity_id' => '12','key' => '47','name' => "Pedro Ascencio Alquisiras"],
            ['fed_entity_id' => '12','key' => '48','name' => "Petatlán"],
            ['fed_entity_id' => '12','key' => '49','name' => "Pilcaya"],
            ['fed_entity_id' => '12','key' => '50','name' => "Pungarabato"],
            ['fed_entity_id' => '12','key' => '51','name' => "Quechultenango"],
            ['fed_entity_id' => '12','key' => '52','name' => "San Luis Acatlán"],
            ['fed_entity_id' => '12','key' => '53','name' => "San Marcos"],
            ['fed_entity_id' => '12','key' => '54','name' => "San Miguel Totolapan"],
            ['fed_entity_id' => '12','key' => '55','name' => "Taxco de Alarcón"],
            ['fed_entity_id' => '12','key' => '56','name' => "Tecoanapa"],
            ['fed_entity_id' => '12','key' => '57','name' => "Técpan de Galeana"],
            ['fed_entity_id' => '12','key' => '58','name' => "Teloloapan"],
            ['fed_entity_id' => '12','key' => '59','name' => "Tepecoacuilco de Trujano"],
            ['fed_entity_id' => '12','key' => '60','name' => "Tetipac"],
            ['fed_entity_id' => '12','key' => '61','name' => "Tixtla de Guerrero"],
            ['fed_entity_id' => '12','key' => '62','name' => "Tlacoachistlahuaca"],
            ['fed_entity_id' => '12','key' => '63','name' => "Tlacoapa"],
            ['fed_entity_id' => '12','key' => '64','name' => "Tlalchapa"],
            ['fed_entity_id' => '12','key' => '65','name' => "Tlalixtaquilla de Maldonado"],
            ['fed_entity_id' => '12','key' => '66','name' => "Tlapa de Comonfort"],
            ['fed_entity_id' => '12','key' => '67','name' => "Tlapehuala"],
            ['fed_entity_id' => '12','key' => '68','name' => "La Unión de Isidoro Montes de Oca"],
            ['fed_entity_id' => '12','key' => '69','name' => "Xalpatláhuac"],
            ['fed_entity_id' => '12','key' => '70','name' => "Xochihuehuetlán"],
            ['fed_entity_id' => '12','key' => '71','name' => "Xochistlahuaca"],
            ['fed_entity_id' => '12','key' => '72','name' => "Zapotitlán Tablas"],
            ['fed_entity_id' => '12','key' => '73','name' => "Zirándaro"],
            ['fed_entity_id' => '12','key' => '74','name' => "Zitlala"],
            ['fed_entity_id' => '12','key' => '75','name' => "Eduardo Neri"],
            ['fed_entity_id' => '12','key' => '76','name' => "Acatepec"],
            ['fed_entity_id' => '12','key' => '77','name' => "Marquelia"],
            ['fed_entity_id' => '12','key' => '78','name' => "Cochoapa el Grande"],
            ['fed_entity_id' => '12','key' => '79','name' => "José Joaquin de Herrera"],
            ['fed_entity_id' => '12','key' => '80','name' => "Juchitán"],
            ['fed_entity_id' => '12','key' => '81','name' => "Iliatenco"],
            ['fed_entity_id' => '13','key' => '1','name' => "Acatlán"],
            ['fed_entity_id' => '13','key' => '2','name' => "Acaxochitlán"],
            ['fed_entity_id' => '13','key' => '3','name' => "Actopan"],
            ['fed_entity_id' => '13','key' => '4','name' => "Agua Blanca de Iturbide"],
            ['fed_entity_id' => '13','key' => '5','name' => "Ajacuba"],
            ['fed_entity_id' => '13','key' => '6','name' => "Alfajayucan"],
            ['fed_entity_id' => '13','key' => '7','name' => "Almoloya"],
            ['fed_entity_id' => '13','key' => '8','name' => "Apan"],
            ['fed_entity_id' => '13','key' => '9','name' => "El Arenal"],
            ['fed_entity_id' => '13','key' => '10','name' => "Atitalaquia"],
            ['fed_entity_id' => '13','key' => '11','name' => "Atlapexco"],
            ['fed_entity_id' => '13','key' => '12','name' => "Atotonilco el Grande"],
            ['fed_entity_id' => '13','key' => '13','name' => "Atotonilco de Tula"],
            ['fed_entity_id' => '13','key' => '14','name' => "Calnali"],
            ['fed_entity_id' => '13','key' => '15','name' => "Cardonal"],
            ['fed_entity_id' => '13','key' => '16','name' => "Cuautepec de Hinojosa"],
            ['fed_entity_id' => '13','key' => '17','name' => "Chapantongo"],
            ['fed_entity_id' => '13','key' => '18','name' => "Chapulhuacán"],
            ['fed_entity_id' => '13','key' => '19','name' => "Chilcuautla"],
            ['fed_entity_id' => '13','key' => '20','name' => "Eloxochitlán"],
            ['fed_entity_id' => '13','key' => '21','name' => "Emiliano Zapata"],
            ['fed_entity_id' => '13','key' => '22','name' => "Epazoyucan"],
            ['fed_entity_id' => '13','key' => '23','name' => "Francisco I. Madero"],
            ['fed_entity_id' => '13','key' => '24','name' => "Huasca de Ocampo"],
            ['fed_entity_id' => '13','key' => '25','name' => "Huautla"],
            ['fed_entity_id' => '13','key' => '26','name' => "Huazalingo"],
            ['fed_entity_id' => '13','key' => '27','name' => "Huehuetla"],
            ['fed_entity_id' => '13','key' => '28','name' => "Huejutla de Reyes"],
            ['fed_entity_id' => '13','key' => '29','name' => "Huichapan"],
            ['fed_entity_id' => '13','key' => '30','name' => "Ixmiquilpan"],
            ['fed_entity_id' => '13','key' => '31','name' => "Jacala de Ledezma"],
            ['fed_entity_id' => '13','key' => '32','name' => "Jaltocán"],
            ['fed_entity_id' => '13','key' => '33','name' => "Juárez Hidalgo"],
            ['fed_entity_id' => '13','key' => '34','name' => "Lolotla"],
            ['fed_entity_id' => '13','key' => '35','name' => "Metepec"],
            ['fed_entity_id' => '13','key' => '36','name' => "San Agustín Metzquititlán"],
            ['fed_entity_id' => '13','key' => '37','name' => "Metztitlán"],
            ['fed_entity_id' => '13','key' => '38','name' => "Mineral del Chico"],
            ['fed_entity_id' => '13','key' => '39','name' => "Mineral del Monte"],
            ['fed_entity_id' => '13','key' => '40','name' => "La Misión"],
            ['fed_entity_id' => '13','key' => '12','name' => "Mixquiahuala de Juárez"],
            ['fed_entity_id' => '13','key' => '13','name' => "Molango de Escamilla"],
            ['fed_entity_id' => '13','key' => '14','name' => "Nicolás Flores"],
            ['fed_entity_id' => '13','key' => '15','name' => "Nopala de Villagrán"],
            ['fed_entity_id' => '13','key' => '45','name' => "Omitlán de Juárez"],
            ['fed_entity_id' => '13','key' => '46','name' => "San Felipe Orizatlán"],
            ['fed_entity_id' => '13','key' => '47','name' => "Pacula"],
            ['fed_entity_id' => '13','key' => '48','name' => "Pachuca de Soto"],
            ['fed_entity_id' => '13','key' => '49','name' => "Pisaflores"],
            ['fed_entity_id' => '13','key' => '50','name' => "Progreso de Obregón"],
            ['fed_entity_id' => '13','key' => '51','name' => "Mineral de la Reforma"],
            ['fed_entity_id' => '13','key' => '52','name' => "San Agustín Tlaxiaca"],
            ['fed_entity_id' => '13','key' => '53','name' => "San Bartolo Tutotepec"],
            ['fed_entity_id' => '13','key' => '54','name' => "San Salvador"],
            ['fed_entity_id' => '13','key' => '55','name' => "Santiago de Anaya"],
            ['fed_entity_id' => '13','key' => '56','name' => "Santiago Tulantepec de Lugo Guerrero"],
            ['fed_entity_id' => '13','key' => '57','name' => "Singuilucan"],
            ['fed_entity_id' => '13','key' => '58','name' => "Tasquillo"],
            ['fed_entity_id' => '13','key' => '59','name' => "Tecozautla"],
            ['fed_entity_id' => '13','key' => '60','name' => "Tenango de Doria"],
            ['fed_entity_id' => '13','key' => '61','name' => "Tepeapulco"],
            ['fed_entity_id' => '13','key' => '62','name' => "Tepehuacán de Guerrero"],
            ['fed_entity_id' => '13','key' => '63','name' => "Tepeji del Río de Ocampo"],
            ['fed_entity_id' => '13','key' => '64','name' => "Tepetitlán"],
            ['fed_entity_id' => '13','key' => '65','name' => "Tetepango"],
            ['fed_entity_id' => '13','key' => '66','name' => "Villa de Tezontepec"],
            ['fed_entity_id' => '13','key' => '67','name' => "Tezontepec de Aldama"],
            ['fed_entity_id' => '13','key' => '68','name' => "Tianguistengo"],
            ['fed_entity_id' => '13','key' => '69','name' => "Tizayuca"],
            ['fed_entity_id' => '13','key' => '70','name' => "Tlahuelilpan"],
            ['fed_entity_id' => '13','key' => '71','name' => "Tlahuiltepa"],
            ['fed_entity_id' => '13','key' => '72','name' => "Tlanalapa"],
            ['fed_entity_id' => '13','key' => '73','name' => "Tlanchinol"],
            ['fed_entity_id' => '13','key' => '74','name' => "Tlaxcoapan"],
            ['fed_entity_id' => '13','key' => '75','name' => "Tolcayuca"],
            ['fed_entity_id' => '13','key' => '76','name' => "Tula de Allende"],
            ['fed_entity_id' => '13','key' => '77','name' => "Tulancingo de Bravo"],
            ['fed_entity_id' => '13','key' => '78','name' => "Xochiatipan"],
            ['fed_entity_id' => '13','key' => '79','name' => "Xochicoatlán"],
            ['fed_entity_id' => '13','key' => '80','name' => "Yahualica"],
            ['fed_entity_id' => '13','key' => '81','name' => "Zacualtipán de Ángeles"],
            ['fed_entity_id' => '13','key' => '82','name' => "Zapotlán de Juárez"],
            ['fed_entity_id' => '13','key' => '83','name' => "Zempoala"],
            ['fed_entity_id' => '13','key' => '84','name' => "Zimapán"],
            ['fed_entity_id' => '14','key' => '1','name' => "Acatic"],
            ['fed_entity_id' => '14','key' => '2','name' => "Acatlán de Juárez"],
            ['fed_entity_id' => '14','key' => '3','name' => "Ahualulco de Mercado"],
            ['fed_entity_id' => '14','key' => '4','name' => "Amacueca"],
            ['fed_entity_id' => '14','key' => '5','name' => "Amatitán"],
            ['fed_entity_id' => '14','key' => '6','name' => "Ameca"],
            ['fed_entity_id' => '14','key' => '7','name' => "San Juanito de Escobedo"],
            ['fed_entity_id' => '14','key' => '8','name' => "Arandas"],
            ['fed_entity_id' => '14','key' => '9','name' => "El Arenal"],
            ['fed_entity_id' => '14','key' => '10','name' => "Atemajac de Brizuela"],
            ['fed_entity_id' => '14','key' => '11','name' => "Atengo"],
            ['fed_entity_id' => '14','key' => '12','name' => "Atenguillo"],
            ['fed_entity_id' => '14','key' => '13','name' => "Atotonilco el Alto"],
            ['fed_entity_id' => '14','key' => '14','name' => "Atoyac"],
            ['fed_entity_id' => '14','key' => '15','name' => "Autlán de Navarro"],
            ['fed_entity_id' => '14','key' => '16','name' => "Ayotlán"],
            ['fed_entity_id' => '14','key' => '17','name' => "Ayutla"],
            ['fed_entity_id' => '14','key' => '18','name' => "La Barca"],
            ['fed_entity_id' => '14','key' => '19','name' => "Bolaños"],
            ['fed_entity_id' => '14','key' => '20','name' => "Cabo Corrientes"],
            ['fed_entity_id' => '14','key' => '21','name' => "Casimiro Castillo"],
            ['fed_entity_id' => '14','key' => '22','name' => "Cihuatlán"],
            ['fed_entity_id' => '14','key' => '23','name' => "Zapotlán el Grande"],
            ['fed_entity_id' => '14','key' => '24','name' => "Cocula"],
            ['fed_entity_id' => '14','key' => '25','name' => "Colotlán"],
            ['fed_entity_id' => '14','key' => '26','name' => "Concepción de Buenos Aires"],
            ['fed_entity_id' => '14','key' => '27','name' => "Cuautitlán de García Barragán"],
            ['fed_entity_id' => '14','key' => '28','name' => "Cuautla"],
            ['fed_entity_id' => '14','key' => '29','name' => "Cuquío"],
            ['fed_entity_id' => '14','key' => '30','name' => "Chapala"],
            ['fed_entity_id' => '14','key' => '31','name' => "Chimaltitán"],
            ['fed_entity_id' => '14','key' => '32','name' => "Chiquilistlán"],
            ['fed_entity_id' => '14','key' => '33','name' => "Degollado"],
            ['fed_entity_id' => '14','key' => '34','name' => "Ejutla"],
            ['fed_entity_id' => '14','key' => '35','name' => "Encarnación de Díaz"],
            ['fed_entity_id' => '14','key' => '36','name' => "Etzatlán"],
            ['fed_entity_id' => '14','key' => '37','name' => "El Grullo"],
            ['fed_entity_id' => '14','key' => '38','name' => "Guachinango"],
            ['fed_entity_id' => '14','key' => '39','name' => "Guadalajara"],
            ['fed_entity_id' => '14','key' => '40','name' => "Hostotipaquillo"],
            ['fed_entity_id' => '14','key' => '12','name' => "Huejúcar"],
            ['fed_entity_id' => '14','key' => '13','name' => "Huejuquilla el Alto"],
            ['fed_entity_id' => '14','key' => '14','name' => "La Huerta"],
            ['fed_entity_id' => '14','key' => '15','name' => "Ixtlahuacán de los Membrillos"],
            ['fed_entity_id' => '14','key' => '45','name' => "Ixtlahuacán del Río"],
            ['fed_entity_id' => '14','key' => '46','name' => "Jalostotitlán"],
            ['fed_entity_id' => '14','key' => '47','name' => "Jamay"],
            ['fed_entity_id' => '14','key' => '48','name' => "Jesús María"],
            ['fed_entity_id' => '14','key' => '49','name' => "Jilotlán de los Dolores"],
            ['fed_entity_id' => '14','key' => '50','name' => "Jocotepec"],
            ['fed_entity_id' => '14','key' => '51','name' => "Juanacatlán"],
            ['fed_entity_id' => '14','key' => '52','name' => "Juchitlán"],
            ['fed_entity_id' => '14','key' => '53','name' => "Lagos de Moreno"],
            ['fed_entity_id' => '14','key' => '54','name' => "El Limón"],
            ['fed_entity_id' => '14','key' => '55','name' => "Magdalena"],
            ['fed_entity_id' => '14','key' => '56','name' => "Santa María del Oro"],
            ['fed_entity_id' => '14','key' => '57','name' => "La Manzanilla de la Paz"],
            ['fed_entity_id' => '14','key' => '58','name' => "Mascota"],
            ['fed_entity_id' => '14','key' => '59','name' => "Mazamitla"],
            ['fed_entity_id' => '14','key' => '60','name' => "Mexticacán"],
            ['fed_entity_id' => '14','key' => '61','name' => "Mezquitic"],
            ['fed_entity_id' => '14','key' => '62','name' => "Mixtlán"],
            ['fed_entity_id' => '14','key' => '63','name' => "Ocotlán"],
            ['fed_entity_id' => '14','key' => '64','name' => "Ojuelos de Jalisco"],
            ['fed_entity_id' => '14','key' => '65','name' => "Pihuamo"],
            ['fed_entity_id' => '14','key' => '66','name' => "Poncitlán"],
            ['fed_entity_id' => '14','key' => '67','name' => "Puerto Vallarta"],
            ['fed_entity_id' => '14','key' => '68','name' => "Villa Purificación"],
            ['fed_entity_id' => '14','key' => '69','name' => "Quitupan"],
            ['fed_entity_id' => '14','key' => '70','name' => "El Salto"],
            ['fed_entity_id' => '14','key' => '71','name' => "San Cristóbal de la Barranca"],
            ['fed_entity_id' => '14','key' => '72','name' => "San Diego de Alejandría"],
            ['fed_entity_id' => '14','key' => '73','name' => "San Juan de los Lagos"],
            ['fed_entity_id' => '14','key' => '74','name' => "San Julián"],
            ['fed_entity_id' => '14','key' => '75','name' => "San Marcos"],
            ['fed_entity_id' => '14','key' => '76','name' => "San Martín de Bolaños"],
            ['fed_entity_id' => '14','key' => '77','name' => "San Martín Hidalgo"],
            ['fed_entity_id' => '14','key' => '78','name' => "San Miguel el Alto"],
            ['fed_entity_id' => '14','key' => '79','name' => "Gómez Farías"],
            ['fed_entity_id' => '14','key' => '80','name' => "San Sebastián del Oeste"],
            ['fed_entity_id' => '14','key' => '81','name' => "Santa María de los Ángeles"],
            ['fed_entity_id' => '14','key' => '82','name' => "Sayula"],
            ['fed_entity_id' => '14','key' => '83','name' => "Tala"],
            ['fed_entity_id' => '14','key' => '84','name' => "Talpa de Allende"],
            ['fed_entity_id' => '14','key' => '85','name' => "Tamazula de Gordiano"],
            ['fed_entity_id' => '14','key' => '86','name' => "Tapalpa"],
            ['fed_entity_id' => '14','key' => '87','name' => "Tecalitlán"],
            ['fed_entity_id' => '14','key' => '88','name' => "Tecolotlán"],
            ['fed_entity_id' => '14','key' => '89','name' => "Techaluta de Montenegro"],
            ['fed_entity_id' => '14','key' => '90','name' => "Tenamaxtlán"],
            ['fed_entity_id' => '14','key' => '91','name' => "Teocaltiche"],
            ['fed_entity_id' => '14','key' => '92','name' => "Teocuitatlán de Corona"],
            ['fed_entity_id' => '14','key' => '93','name' => "Tepatitlán de Morelos"],
            ['fed_entity_id' => '14','key' => '94','name' => "Tequila"],
            ['fed_entity_id' => '14','key' => '95','name' => "Teuchitlán"],
            ['fed_entity_id' => '14','key' => '96','name' => "Tizapán el Alto"],
            ['fed_entity_id' => '14','key' => '97','name' => "Tlajomulco de Zúñiga"],
            ['fed_entity_id' => '14','key' => '98','name' => "Tlaquepaque"],
            ['fed_entity_id' => '14','key' => '99','name' => "Tolimán"],
            ['fed_entity_id' => '14','key' => '100','name' => "Tomatlán"],
            ['fed_entity_id' => '14','key' => '101','name' => "Tonalá"],
            ['fed_entity_id' => '14','key' => '102','name' => "Tonaya"],
            ['fed_entity_id' => '14','key' => '103','name' => "Tonila"],
            ['fed_entity_id' => '14','key' => '104','name' => "Totatiche"],
            ['fed_entity_id' => '14','key' => '105','name' => "Tototlán"],
            ['fed_entity_id' => '14','key' => '106','name' => "Tuxcacuesco"],
            ['fed_entity_id' => '14','key' => '107','name' => "Tuxcueca"],
            ['fed_entity_id' => '14','key' => '108','name' => "Tuxpan"],
            ['fed_entity_id' => '14','key' => '109','name' => "Unión de San Antonio"],
            ['fed_entity_id' => '14','key' => '110','name' => "Unión de Tula"],
            ['fed_entity_id' => '14','key' => '111','name' => "Valle de Guadalupe"],
            ['fed_entity_id' => '14','key' => '112','name' => "Valle de Juárez"],
            ['fed_entity_id' => '14','key' => '113','name' => "San Gabriel"],
            ['fed_entity_id' => '14','key' => '114','name' => "Villa Corona"],
            ['fed_entity_id' => '14','key' => '115','name' => "Villa Guerrero"],
            ['fed_entity_id' => '14','key' => '116','name' => "Villa Hidalgo"],
            ['fed_entity_id' => '14','key' => '117','name' => "Cañadas de Obregón"],
            ['fed_entity_id' => '14','key' => '118','name' => "Yahualica de González Gallo"],
            ['fed_entity_id' => '14','key' => '119','name' => "Zacoalco de Torres"],
            ['fed_entity_id' => '14','key' => '120','name' => "Zapopan"],
            ['fed_entity_id' => '14','key' => '121','name' => "Zapotiltic"],
            ['fed_entity_id' => '14','key' => '122','name' => "Zapotitlán de Vadillo"],
            ['fed_entity_id' => '14','key' => '123','name' => "Zapotlán del Rey"],
            ['fed_entity_id' => '14','key' => '124','name' => "Zapotlanejo"],
            ['fed_entity_id' => '14','key' => '125','name' => "San Ignacio Cerro Gordo"],
            ['fed_entity_id' => '15','key' => '1','name' => "Acambay"],
            ['fed_entity_id' => '15','key' => '2','name' => "Acolman"],
            ['fed_entity_id' => '15','key' => '3','name' => "Aculco"],
            ['fed_entity_id' => '15','key' => '4','name' => "Almoloya de Alquisiras"],
            ['fed_entity_id' => '15','key' => '5','name' => "Almoloya de Juárez"],
            ['fed_entity_id' => '15','key' => '6','name' => "Almoloya del Río"],
            ['fed_entity_id' => '15','key' => '7','name' => "Amanalco"],
            ['fed_entity_id' => '15','key' => '8','name' => "Amatepec"],
            ['fed_entity_id' => '15','key' => '9','name' => "Amecameca"],
            ['fed_entity_id' => '15','key' => '10','name' => "Apaxco"],
            ['fed_entity_id' => '15','key' => '11','name' => "Atenco"],
            ['fed_entity_id' => '15','key' => '12','name' => "Atizapán"],
            ['fed_entity_id' => '15','key' => '13','name' => "Atizapán de Zaragoza"],
            ['fed_entity_id' => '15','key' => '14','name' => "Atlacomulco"],
            ['fed_entity_id' => '15','key' => '15','name' => "Atlautla"],
            ['fed_entity_id' => '15','key' => '16','name' => "Axapusco"],
            ['fed_entity_id' => '15','key' => '17','name' => "Ayapango"],
            ['fed_entity_id' => '15','key' => '18','name' => "Calimaya"],
            ['fed_entity_id' => '15','key' => '19','name' => "Capulhuac"],
            ['fed_entity_id' => '15','key' => '20','name' => "Coacalco de Berriozábal"],
            ['fed_entity_id' => '15','key' => '21','name' => "Coatepec Harinas"],
            ['fed_entity_id' => '15','key' => '22','name' => "Cocotitlán"],
            ['fed_entity_id' => '15','key' => '23','name' => "Coyotepec"],
            ['fed_entity_id' => '15','key' => '24','name' => "Cuautitlán"],
            ['fed_entity_id' => '15','key' => '25','name' => "Chalco"],
            ['fed_entity_id' => '15','key' => '26','name' => "Chapa de Mota"],
            ['fed_entity_id' => '15','key' => '27','name' => "Chapultepec"],
            ['fed_entity_id' => '15','key' => '28','name' => "Chiautla"],
            ['fed_entity_id' => '15','key' => '29','name' => "Chicoloapan"],
            ['fed_entity_id' => '15','key' => '30','name' => "Chiconcuac"],
            ['fed_entity_id' => '15','key' => '31','name' => "Chimalhuacán"],
            ['fed_entity_id' => '15','key' => '32','name' => "Donato Guerra"],
            ['fed_entity_id' => '15','key' => '33','name' => "Ecatepec de Morelos"],
            ['fed_entity_id' => '15','key' => '34','name' => "Ecatzingo"],
            ['fed_entity_id' => '15','key' => '35','name' => "Huehuetoca"],
            ['fed_entity_id' => '15','key' => '36','name' => "Hueypoxtla"],
            ['fed_entity_id' => '15','key' => '37','name' => "Huixquilucan"],
            ['fed_entity_id' => '15','key' => '38','name' => "Isidro Fabela"],
            ['fed_entity_id' => '15','key' => '39','name' => "Ixtapaluca"],
            ['fed_entity_id' => '15','key' => '40','name' => "Ixtapan de la Sal"],
            ['fed_entity_id' => '15','key' => '41','name' => "Ixtapan del Oro"],
            ['fed_entity_id' => '15','key' => '42','name' => "Ixtlahuaca"],
            ['fed_entity_id' => '15','key' => '43','name' => "Xalatlaco"],
            ['fed_entity_id' => '15','key' => '44','name' => "Jaltenco"],
            ['fed_entity_id' => '15','key' => '45','name' => "Jilotepec"],
            ['fed_entity_id' => '15','key' => '46','name' => "Jilotzingo"],
            ['fed_entity_id' => '15','key' => '47','name' => "Jiquipilco"],
            ['fed_entity_id' => '15','key' => '48','name' => "Jocotitlán"],
            ['fed_entity_id' => '15','key' => '49','name' => "Joquicingo"],
            ['fed_entity_id' => '15','key' => '50','name' => "Juchitepec"],
            ['fed_entity_id' => '15','key' => '51','name' => "Lerma"],
            ['fed_entity_id' => '15','key' => '52','name' => "Malinalco"],
            ['fed_entity_id' => '15','key' => '53','name' => "Melchor Ocampo"],
            ['fed_entity_id' => '15','key' => '54','name' => "Metepec"],
            ['fed_entity_id' => '15','key' => '55','name' => "Mexicaltzingo"],
            ['fed_entity_id' => '15','key' => '56','name' => "Morelos"],
            ['fed_entity_id' => '15','key' => '57','name' => "Naucalpan de Juárez"],
            ['fed_entity_id' => '15','key' => '58','name' => "Nezahualcóyotl"],
            ['fed_entity_id' => '15','key' => '59','name' => "Nextlalpan"],
            ['fed_entity_id' => '15','key' => '60','name' => "Nicolás Romero"],
            ['fed_entity_id' => '15','key' => '61','name' => "Nopaltepec"],
            ['fed_entity_id' => '15','key' => '62','name' => "Ocoyoacac"],
            ['fed_entity_id' => '15','key' => '63','name' => "Ocuilan"],
            ['fed_entity_id' => '15','key' => '64','name' => "El Oro"],
            ['fed_entity_id' => '15','key' => '65','name' => "Otumba"],
            ['fed_entity_id' => '15','key' => '66','name' => "Otzoloapan"],
            ['fed_entity_id' => '15','key' => '67','name' => "Otzolotepec"],
            ['fed_entity_id' => '15','key' => '68','name' => "Ozumba"],
            ['fed_entity_id' => '15','key' => '69','name' => "Papalotla"],
            ['fed_entity_id' => '15','key' => '70','name' => "La Paz"],
            ['fed_entity_id' => '15','key' => '71','name' => "Polotitlán"],
            ['fed_entity_id' => '15','key' => '72','name' => "Rayón"],
            ['fed_entity_id' => '15','key' => '73','name' => "San Antonio la Isla"],
            ['fed_entity_id' => '15','key' => '74','name' => "San Felipe del Progreso"],
            ['fed_entity_id' => '15','key' => '75','name' => "San Martín de las Pirámides"],
            ['fed_entity_id' => '15','key' => '76','name' => "San Mateo Atenco"],
            ['fed_entity_id' => '15','key' => '77','name' => "San Simón de Guerrero"],
            ['fed_entity_id' => '15','key' => '78','name' => "Santo Tomás"],
            ['fed_entity_id' => '15','key' => '79','name' => "Soyaniquilpan de Juárez"],
            ['fed_entity_id' => '15','key' => '80','name' => "Sultepec"],
            ['fed_entity_id' => '15','key' => '81','name' => "Tecámac"],
            ['fed_entity_id' => '15','key' => '82','name' => "Tejupilco"],
            ['fed_entity_id' => '15','key' => '83','name' => "Temamatla"],
            ['fed_entity_id' => '15','key' => '84','name' => "Temascalapa"],
            ['fed_entity_id' => '15','key' => '85','name' => "Temascalcingo"],
            ['fed_entity_id' => '15','key' => '86','name' => "Temascaltepec"],
            ['fed_entity_id' => '15','key' => '87','name' => "Temoaya"],
            ['fed_entity_id' => '15','key' => '88','name' => "Tenancingo"],
            ['fed_entity_id' => '15','key' => '89','name' => "Tenango del Aire"],
            ['fed_entity_id' => '15','key' => '90','name' => "Tenango del Valle"],
            ['fed_entity_id' => '15','key' => '91','name' => "Teoloyucan"],
            ['fed_entity_id' => '15','key' => '92','name' => "Teotihuacán"],
            ['fed_entity_id' => '15','key' => '93','name' => "Tepetlaoxtoc"],
            ['fed_entity_id' => '15','key' => '94','name' => "Tepetlixpa"],
            ['fed_entity_id' => '15','key' => '95','name' => "Tepotzotlán"],
            ['fed_entity_id' => '15','key' => '96','name' => "Tequixquiac"],
            ['fed_entity_id' => '15','key' => '97','name' => "Texcaltitlán"],
            ['fed_entity_id' => '15','key' => '98','name' => "Texcalyacac"],
            ['fed_entity_id' => '15','key' => '99','name' => "Texcoco"],
            ['fed_entity_id' => '15','key' => '100','name' => "Tezoyuca"],
            ['fed_entity_id' => '15','key' => '101','name' => "Tianguistenco"],
            ['fed_entity_id' => '15','key' => '102','name' => "Timilpan"],
            ['fed_entity_id' => '15','key' => '103','name' => "Tlalmanalco"],
            ['fed_entity_id' => '15','key' => '104','name' => "Tlalnepantla de Baz"],
            ['fed_entity_id' => '15','key' => '105','name' => "Tlatlaya"],
            ['fed_entity_id' => '15','key' => '106','name' => "Toluca"],
            ['fed_entity_id' => '15','key' => '107','name' => "Tonatico"],
            ['fed_entity_id' => '15','key' => '108','name' => "Tultepec"],
            ['fed_entity_id' => '15','key' => '109','name' => "Tultitlán"],
            ['fed_entity_id' => '15','key' => '110','name' => "Valle de Bravo"],
            ['fed_entity_id' => '15','key' => '111','name' => "Villa de Allende"],
            ['fed_entity_id' => '15','key' => '112','name' => "Villa del Carbón"],
            ['fed_entity_id' => '15','key' => '113','name' => "Villa Guerrero"],
            ['fed_entity_id' => '15','key' => '114','name' => "Villa Victoria"],
            ['fed_entity_id' => '15','key' => '115','name' => "Xonacatlán"],
            ['fed_entity_id' => '15','key' => '116','name' => "Zacazonapan"],
            ['fed_entity_id' => '15','key' => '117','name' => "Zacualpan"],
            ['fed_entity_id' => '15','key' => '118','name' => "Zinacantepec"],
            ['fed_entity_id' => '15','key' => '119','name' => "Zumpahuacán"],
            ['fed_entity_id' => '15','key' => '120','name' => "Zumpango"],
            ['fed_entity_id' => '15','key' => '121','name' => "Cuautitlán Izcalli"],
            ['fed_entity_id' => '15','key' => '122','name' => "Valle de Chalco Solidaridad"],
            ['fed_entity_id' => '15','key' => '123','name' => "Luvianos"],
            ['fed_entity_id' => '15','key' => '124','name' => "San José del Rincón"],
            ['fed_entity_id' => '15','key' => '125','name' => "Tonanitla"],
            ['fed_entity_id' => '16','key' => '1','name' => "Acuitzio"],
            ['fed_entity_id' => '16','key' => '2','name' => "Aguililla"],
            ['fed_entity_id' => '16','key' => '3','name' => "Álvaro Obregón"],
            ['fed_entity_id' => '16','key' => '4','name' => "Angamacutiro"],
            ['fed_entity_id' => '16','key' => '5','name' => "Angangueo"],
            ['fed_entity_id' => '16','key' => '6','name' => "Apatzingán"],
            ['fed_entity_id' => '16','key' => '7','name' => "Aporo"],
            ['fed_entity_id' => '16','key' => '8','name' => "Aquila"],
            ['fed_entity_id' => '16','key' => '9','name' => "Ario"],
            ['fed_entity_id' => '16','key' => '10','name' => "Arteaga"],
            ['fed_entity_id' => '16','key' => '11','name' => "Briseñas"],
            ['fed_entity_id' => '16','key' => '12','name' => "Buenavista"],
            ['fed_entity_id' => '16','key' => '13','name' => "Carácuaro"],
            ['fed_entity_id' => '16','key' => '14','name' => "Coahuayana"],
            ['fed_entity_id' => '16','key' => '15','name' => "Coalcomán de Vázquez Pallares"],
            ['fed_entity_id' => '16','key' => '16','name' => "Coeneo"],
            ['fed_entity_id' => '16','key' => '17','name' => "Contepec"],
            ['fed_entity_id' => '16','key' => '18','name' => "Copándaro"],
            ['fed_entity_id' => '16','key' => '19','name' => "Cotija"],
            ['fed_entity_id' => '16','key' => '20','name' => "Cuitzeo"],
            ['fed_entity_id' => '16','key' => '21','name' => "Charapan"],
            ['fed_entity_id' => '16','key' => '22','name' => "Charo"],
            ['fed_entity_id' => '16','key' => '23','name' => "Chavinda"],
            ['fed_entity_id' => '16','key' => '24','name' => "Cherán"],
            ['fed_entity_id' => '16','key' => '25','name' => "Chilchota"],
            ['fed_entity_id' => '16','key' => '26','name' => "Chinicuila"],
            ['fed_entity_id' => '16','key' => '27','name' => "Chucándiro"],
            ['fed_entity_id' => '16','key' => '28','name' => "Churintzio"],
            ['fed_entity_id' => '16','key' => '29','name' => "Churumuco"],
            ['fed_entity_id' => '16','key' => '30','name' => "Ecuandureo"],
            ['fed_entity_id' => '16','key' => '31','name' => "Epitacio Huerta"],
            ['fed_entity_id' => '16','key' => '32','name' => "Erongarícuaro"],
            ['fed_entity_id' => '16','key' => '33','name' => "Gabriel Zamora"],
            ['fed_entity_id' => '16','key' => '34','name' => "Hidalgo"],
            ['fed_entity_id' => '16','key' => '35','name' => "La Huacana"],
            ['fed_entity_id' => '16','key' => '36','name' => "Huandacareo"],
            ['fed_entity_id' => '16','key' => '37','name' => "Huaniqueo"],
            ['fed_entity_id' => '16','key' => '38','name' => "Huetamo"],
            ['fed_entity_id' => '16','key' => '39','name' => "Huiramba"],
            ['fed_entity_id' => '16','key' => '40','name' => "Indaparapeo"],
            ['fed_entity_id' => '16','key' => '12','name' => "Irimbo"],
            ['fed_entity_id' => '16','key' => '13','name' => "Ixtlán"],
            ['fed_entity_id' => '16','key' => '14','name' => "Jacona"],
            ['fed_entity_id' => '16','key' => '15','name' => "Jiménez"],
            ['fed_entity_id' => '16','key' => '45','name' => "Jiquilpan"],
            ['fed_entity_id' => '16','key' => '46','name' => "Juárez"],
            ['fed_entity_id' => '16','key' => '47','name' => "Jungapeo"],
            ['fed_entity_id' => '16','key' => '48','name' => "Lagunillas"],
            ['fed_entity_id' => '16','key' => '49','name' => "Madero"],
            ['fed_entity_id' => '16','key' => '50','name' => "Maravatío"],
            ['fed_entity_id' => '16','key' => '51','name' => "Marcos Castellanos"],
            ['fed_entity_id' => '16','key' => '52','name' => "Lázaro Cárdenas"],
            ['fed_entity_id' => '16','key' => '53','name' => "Morelia"],
            ['fed_entity_id' => '16','key' => '54','name' => "Morelos"],
            ['fed_entity_id' => '16','key' => '55','name' => "Múgica"],
            ['fed_entity_id' => '16','key' => '56','name' => "Nahuatzen"],
            ['fed_entity_id' => '16','key' => '57','name' => "Nocupétaro"],
            ['fed_entity_id' => '16','key' => '58','name' => "Nuevo Parangaricutiro"],
            ['fed_entity_id' => '16','key' => '59','name' => "Nuevo Urecho"],
            ['fed_entity_id' => '16','key' => '60','name' => "Numarán"],
            ['fed_entity_id' => '16','key' => '61','name' => "Ocampo"],
            ['fed_entity_id' => '16','key' => '62','name' => "Pajacuarán"],
            ['fed_entity_id' => '16','key' => '63','name' => "Panindícuaro"],
            ['fed_entity_id' => '16','key' => '64','name' => "Parácuaro"],
            ['fed_entity_id' => '16','key' => '65','name' => "Paracho"],
            ['fed_entity_id' => '16','key' => '66','name' => "Pátzcuaro"],
            ['fed_entity_id' => '16','key' => '67','name' => "Penjamillo"],
            ['fed_entity_id' => '16','key' => '68','name' => "Peribán"],
            ['fed_entity_id' => '16','key' => '69','name' => "La Piedad"],
            ['fed_entity_id' => '16','key' => '70','name' => "Purépero"],
            ['fed_entity_id' => '16','key' => '71','name' => "Puruándiro"],
            ['fed_entity_id' => '16','key' => '72','name' => "Queréndaro"],
            ['fed_entity_id' => '16','key' => '73','name' => "Quiroga"],
            ['fed_entity_id' => '16','key' => '74','name' => "Cojumatlán de Régules"],
            ['fed_entity_id' => '16','key' => '75','name' => "Los Reyes"],
            ['fed_entity_id' => '16','key' => '76','name' => "Sahuayo"],
            ['fed_entity_id' => '16','key' => '77','name' => "San Lucas"],
            ['fed_entity_id' => '16','key' => '78','name' => "Santa Ana Maya"],
            ['fed_entity_id' => '16','key' => '79','name' => "Salvador Escalante"],
            ['fed_entity_id' => '16','key' => '80','name' => "Senguio"],
            ['fed_entity_id' => '16','key' => '81','name' => "Susupuato"],
            ['fed_entity_id' => '16','key' => '82','name' => "Tacámbaro"],
            ['fed_entity_id' => '16','key' => '83','name' => "Tancítaro"],
            ['fed_entity_id' => '16','key' => '84','name' => "Tangamandapio"],
            ['fed_entity_id' => '16','key' => '85','name' => "Tangancícuaro"],
            ['fed_entity_id' => '16','key' => '86','name' => "Tanhuato"],
            ['fed_entity_id' => '16','key' => '87','name' => "Taretan"],
            ['fed_entity_id' => '16','key' => '88','name' => "Tarímbaro"],
            ['fed_entity_id' => '16','key' => '89','name' => "Tepalcatepec"],
            ['fed_entity_id' => '16','key' => '90','name' => "Tingambato"],
            ['fed_entity_id' => '16','key' => '91','name' => "Tingüindín"],
            ['fed_entity_id' => '16','key' => '92','name' => "Tiquicheo de Nicolás Romero"],
            ['fed_entity_id' => '16','key' => '93','name' => "Tlalpujahua"],
            ['fed_entity_id' => '16','key' => '94','name' => "Tlazazalca"],
            ['fed_entity_id' => '16','key' => '95','name' => "Tocumbo"],
            ['fed_entity_id' => '16','key' => '96','name' => "Tumbiscatío"],
            ['fed_entity_id' => '16','key' => '97','name' => "Turicato"],
            ['fed_entity_id' => '16','key' => '98','name' => "Tuxpan"],
            ['fed_entity_id' => '16','key' => '99','name' => "Tuzantla"],
            ['fed_entity_id' => '16','key' => '100','name' => "Tzintzuntzan"],
            ['fed_entity_id' => '16','key' => '101','name' => "Tzitzio"],
            ['fed_entity_id' => '16','key' => '102','name' => "Uruapan"],
            ['fed_entity_id' => '16','key' => '103','name' => "Venustiano Carranza"],
            ['fed_entity_id' => '16','key' => '104','name' => "Villamar"],
            ['fed_entity_id' => '16','key' => '105','name' => "Vista Hermosa"],
            ['fed_entity_id' => '16','key' => '106','name' => "Yurécuaro"],
            ['fed_entity_id' => '16','key' => '107','name' => "Zacapu"],
            ['fed_entity_id' => '16','key' => '108','name' => "Zamora"],
            ['fed_entity_id' => '16','key' => '109','name' => "Zináparo"],
            ['fed_entity_id' => '16','key' => '110','name' => "Zinapécuaro"],
            ['fed_entity_id' => '16','key' => '111','name' => "Ziracuaretiro"],
            ['fed_entity_id' => '16','key' => '112','name' => "Zitácuaro"],
            ['fed_entity_id' => '16','key' => '113','name' => "José Sixto Verduzco"],
            ['fed_entity_id' => '17','key' => '1','name' => "Amacuzac"],
            ['fed_entity_id' => '17','key' => '2','name' => "Atlatlahucan"],
            ['fed_entity_id' => '17','key' => '3','name' => "Axochiapan"],
            ['fed_entity_id' => '17','key' => '4','name' => "Ayala"],
            ['fed_entity_id' => '17','key' => '5','name' => "Coatlán del Río"],
            ['fed_entity_id' => '17','key' => '6','name' => "Cuautla"],
            ['fed_entity_id' => '17','key' => '7','name' => "Cuernavaca"],
            ['fed_entity_id' => '17','key' => '8','name' => "Emiliano Zapata"],
            ['fed_entity_id' => '17','key' => '9','name' => "Huitzilac"],
            ['fed_entity_id' => '17','key' => '10','name' => "Jantetelco"],
            ['fed_entity_id' => '17','key' => '11','name' => "Jiutepec"],
            ['fed_entity_id' => '17','key' => '12','name' => "Jojutla"],
            ['fed_entity_id' => '17','key' => '13','name' => "Jonacatepec"],
            ['fed_entity_id' => '17','key' => '14','name' => "Mazatepec"],
            ['fed_entity_id' => '17','key' => '15','name' => "Miacatlán"],
            ['fed_entity_id' => '17','key' => '16','name' => "Ocuituco"],
            ['fed_entity_id' => '17','key' => '17','name' => "Puente de Ixtla"],
            ['fed_entity_id' => '17','key' => '18','name' => "Temixco"],
            ['fed_entity_id' => '17','key' => '19','name' => "Tepalcingo"],
            ['fed_entity_id' => '17','key' => '20','name' => "Tepoztlán"],
            ['fed_entity_id' => '17','key' => '21','name' => "Tetecala"],
            ['fed_entity_id' => '17','key' => '22','name' => "Tetela del Volcán"],
            ['fed_entity_id' => '17','key' => '23','name' => "Tlalnepantla"],
            ['fed_entity_id' => '17','key' => '24','name' => "Tlaltizapán"],
            ['fed_entity_id' => '17','key' => '25','name' => "Tlaquiltenango"],
            ['fed_entity_id' => '17','key' => '26','name' => "Tlayacapan"],
            ['fed_entity_id' => '17','key' => '27','name' => "Totolapan"],
            ['fed_entity_id' => '17','key' => '28','name' => "Xochitepec"],
            ['fed_entity_id' => '17','key' => '29','name' => "Yautepec"],
            ['fed_entity_id' => '17','key' => '30','name' => "Yecapixtla"],
            ['fed_entity_id' => '17','key' => '31','name' => "Zacatepec"],
            ['fed_entity_id' => '17','key' => '32','name' => "Zacualpan"],
            ['fed_entity_id' => '17','key' => '33','name' => "Temoac"],
            ['fed_entity_id' => '18','key' => '1','name' => "Acaponeta"],
            ['fed_entity_id' => '18','key' => '2','name' => "Ahuacatlán"],
            ['fed_entity_id' => '18','key' => '3','name' => "Amatlán de Cañas"],
            ['fed_entity_id' => '18','key' => '4','name' => "Compostela"],
            ['fed_entity_id' => '18','key' => '5','name' => "Huajicori"],
            ['fed_entity_id' => '18','key' => '6','name' => "Ixtlán del Río"],
            ['fed_entity_id' => '18','key' => '7','name' => "Jala"],
            ['fed_entity_id' => '18','key' => '8','name' => "Xalisco"],
            ['fed_entity_id' => '18','key' => '9','name' => "Del Nayar"],
            ['fed_entity_id' => '18','key' => '10','name' => "Rosamorada"],
            ['fed_entity_id' => '18','key' => '11','name' => "Ruíz"],
            ['fed_entity_id' => '18','key' => '12','name' => "San Blas"],
            ['fed_entity_id' => '18','key' => '13','name' => "San Pedro Lagunillas"],
            ['fed_entity_id' => '18','key' => '14','name' => "Santa María del Oro"],
            ['fed_entity_id' => '18','key' => '15','name' => "Santiago Ixcuintla"],
            ['fed_entity_id' => '18','key' => '16','name' => "Tecuala"],
            ['fed_entity_id' => '18','key' => '17','name' => "Tepic"],
            ['fed_entity_id' => '18','key' => '18','name' => "Tuxpan"],
            ['fed_entity_id' => '18','key' => '19','name' => "La Yesca"],
            ['fed_entity_id' => '18','key' => '20','name' => "Bahía de Banderas"],
            ['fed_entity_id' => '19','key' => '1','name' => "Abasolo"],
            ['fed_entity_id' => '19','key' => '2','name' => "Agualeguas"],
            ['fed_entity_id' => '19','key' => '3','name' => "Los Aldamas"],
            ['fed_entity_id' => '19','key' => '4','name' => "Allende"],
            ['fed_entity_id' => '19','key' => '5','name' => "Anáhuac"],
            ['fed_entity_id' => '19','key' => '6','name' => "Apodaca"],
            ['fed_entity_id' => '19','key' => '7','name' => "Aramberri"],
            ['fed_entity_id' => '19','key' => '8','name' => "Bustamante"],
            ['fed_entity_id' => '19','key' => '9','name' => "Cadereyta Jiménez"],
            ['fed_entity_id' => '19','key' => '10','name' => "Carmen"],
            ['fed_entity_id' => '19','key' => '11','name' => "Cerralvo"],
            ['fed_entity_id' => '19','key' => '12','name' => "Ciénega de Flores"],
            ['fed_entity_id' => '19','key' => '13','name' => "China"],
            ['fed_entity_id' => '19','key' => '14','name' => "Dr. Arroyo"],
            ['fed_entity_id' => '19','key' => '15','name' => "Dr. Coss"],
            ['fed_entity_id' => '19','key' => '16','name' => "Dr. González"],
            ['fed_entity_id' => '19','key' => '17','name' => "Galeana"],
            ['fed_entity_id' => '19','key' => '18','name' => "García"],
            ['fed_entity_id' => '19','key' => '19','name' => "San Pedro Garza García"],
            ['fed_entity_id' => '19','key' => '20','name' => "Gral. Bravo"],
            ['fed_entity_id' => '19','key' => '21','name' => "Gral. Escobedo"],
            ['fed_entity_id' => '19','key' => '22','name' => "Gral. Terán"],
            ['fed_entity_id' => '19','key' => '23','name' => "Gral. Treviño"],
            ['fed_entity_id' => '19','key' => '24','name' => "Gral. Zaragoza"],
            ['fed_entity_id' => '19','key' => '25','name' => "Gral. Zuazua"],
            ['fed_entity_id' => '19','key' => '26','name' => "Guadalupe"],
            ['fed_entity_id' => '19','key' => '27','name' => "Los Herreras"],
            ['fed_entity_id' => '19','key' => '28','name' => "Higueras"],
            ['fed_entity_id' => '19','key' => '29','name' => "Hualahuises"],
            ['fed_entity_id' => '19','key' => '30','name' => "Iturbide"],
            ['fed_entity_id' => '19','key' => '31','name' => "Juárez"],
            ['fed_entity_id' => '19','key' => '32','name' => "Lampazos de Naranjo"],
            ['fed_entity_id' => '19','key' => '33','name' => "Linares"],
            ['fed_entity_id' => '19','key' => '34','name' => "Marín"],
            ['fed_entity_id' => '19','key' => '35','name' => "Melchor Ocampo"],
            ['fed_entity_id' => '19','key' => '36','name' => "Mier y Noriega"],
            ['fed_entity_id' => '19','key' => '37','name' => "Mina"],
            ['fed_entity_id' => '19','key' => '38','name' => "Montemorelos"],
            ['fed_entity_id' => '19','key' => '39','name' => "Monterrey"],
            ['fed_entity_id' => '19','key' => '40','name' => "Parás"],
            ['fed_entity_id' => '19','key' => '12','name' => "Pesquería"],
            ['fed_entity_id' => '19','key' => '13','name' => "Los Ramones"],
            ['fed_entity_id' => '19','key' => '14','name' => "Rayones"],
            ['fed_entity_id' => '19','key' => '15','name' => "Sabinas Hidalgo"],
            ['fed_entity_id' => '19','key' => '45','name' => "Salinas Victoria"],
            ['fed_entity_id' => '19','key' => '46','name' => "San Nicolás de los Garza"],
            ['fed_entity_id' => '19','key' => '47','name' => "Hidalgo"],
            ['fed_entity_id' => '19','key' => '48','name' => "Santa Catarina"],
            ['fed_entity_id' => '19','key' => '49','name' => "Santiago"],
            ['fed_entity_id' => '19','key' => '50','name' => "Vallecillo"],
            ['fed_entity_id' => '19','key' => '51','name' => "Villaldama"],
            ['fed_entity_id' => '20','key' => '1','name' => "Abejones"],
            ['fed_entity_id' => '20', 'key' => '2','name' => "Acatlán de Pérez Figueroa"]];

        foreach ($municipio as $m){
            $muni = new Municipality();
            $muni->municipality_name = $m['name'];
            $muni->municipality_key = $m['key'];
            $muni->fed_entity_id = $m['fed_entity_id'];
            $muni->save();
        }
    }
}
